
python csv_transpose.py ../v1 v1
python csv_transpose.py ../v2 v2
python csv_transpose.py ../v3 v3
python csv_transpose.py ../v4 v4
python csv_transpose.py ../v5 v5
python csv_transpose.py ../v6 v6
python csv_transpose.py ../v7 v7
python csv_transpose.py ../v8 v8
python csv_transpose.py ../v9 v9
python csv_transpose.py ../v10 v10
python csv_transpose.py ../v11 v11
python csv_transpose.py ../v12 v12
python csv_transpose.py ../v13 v13
python csv_transpose.py ../v14 v14
python csv_transpose.py ../v15 v15
python csv_transpose.py ../v16 v16
python csv_transpose.py ../v17 v17
python csv_transpose.py ../v18 v18
python csv_transpose.py ../v19 v19
python csv_transpose.py ../v20 v20
python csv_transpose.py ../v21 v21 
python csv_transpose.py ../v21 v21
python csv_transpose.py ../v22 v22
python csv_transpose.py ../v23 v23
python csv_transpose.py ../v24 v24
python csv_transpose.py ../v25 v25